agent:
  max_steps: 35
  reasoning: true
  streaming: true

llm_profiles:
  manager:
    provider: OpenRouter
    model: mistralai/devstral-2512:free
    temperature: 0.2

  executor:
    provider: OpenRouter
    model: mistralai/devstral-2512:free
    temperature: 0.2

  codeact:
    provider: OpenRouter
    model: mistralai/devstral-2512:free
    temperature: 0.2

  app_opener:
    provider: OpenRouter
    model: mistralai/devstral-2512:free
    temperature: 0.0

